import type { Metadata } from "next";

import { IBM_Plex_Sans, DM_Sans, Outfit } from 'next/font/google';

import "./globals.css";
import Providers from "./providers/providers";
import { ToastContainer } from "react-toastify";



const ibm = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-ibm",
});

const dm = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm",
});
const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-outfit',

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en" className={`${ibm.variable} ${dm.variable} ${outfit.variable}`}>
      <body className="antialiased">
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss={false}
          draggable
          pauseOnHover
          theme="colored"
        />
        <Providers>{children}</Providers>
      </body>

    </html>
  );
}
